# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oFO_3N9ZDoKQVWoSaIvWtM5R4Mv699-k
"""

import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt

mnist=tf.keras.datasets.fashion_mnist

(training_images,training_labels),(testing_images,testing_labels)=mnist.load_data()

plt.imshow(training_images[52])
print(training_images[52])
print(training_labels[52])

training_images=training_images/255
testing_images=testing_images/255

model = tf.keras.models.Sequential([tf.keras.layers.Flatten(), 
                                    tf.keras.layers.Dense(128, activation=tf.nn.relu), 
                                    tf.keras.layers.Dense(10, activation=tf.nn.softmax)])

model.compile(optimizer = tf.train.AdamOptimizer(),
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(training_images, training_labels, epochs=10)

model.evaluate(testing_images,testing_labels)